name: Build FileUploader Plugin

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: |
          cd fileuploader-kiwiirc-plugin
          yarn install

      - name: Build plugin
        run: |
          cd fileuploader-kiwiirc-plugin
          yarn build

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: plugin-build
          path: fileuploader-kiwiirc-plugin/build/
